targets:
  $default:
    sources:
      # - test_driver/**        # by default, build runner will not generate code in the test_driver folder
      - integration_test/**   # by default, build runner will not generate code in the integration_test folder
      # - test/**
      # - lib/**
      # - $package$
    builders:
      bdd_widget_test|featureBuilder:
        # options:
          # stepFolderName: steps  # this trick is required to share steps between widget and integration tests
          # stepFolderName: ../../integration_test  # this trick is required to share steps between widget and integration tests
        generate_for:
          - integration_test/**

